var artists = [
    { title: 'The Weeknd'},
    { title: 'Ed Sheeran'},
    { title: 'Taylor Swift'},
    { title: 'David Guetta'},
    { title: 'Sam Smith'},
    { title: 'Justin Bieber'},
    { title: 'Harry Styles'},
    { title: 'Rihanna'},
    { title: 'Bad Bunny	'},
    { title: 'Drake	' },
    { title: 'Dua Lipa' },
    { title: 'Coldplay' },
    { title: 'Eminem' },
    { title: 'Imagine Dragons' },
    { title: 'Ariana Grande ' },
    { title: 'Shakira' },
    { title: 'Doja Cat' },
    { title: 'Post Malone' },
    { title: 'Elton John' },
    { title: 'Bruno Mars' },
    { title: 'Kanye West' },
    { title: 'Billie Eilish' },
    { title: 'J Balvin' },
    { title: 'Khalid' }
    // etc
  ];

var albums = [
    {title: '÷ (Deluxe)'},
    {title: 'beerbongs & bentleys'},
    {title: 'Dua Lipa (Complete Edition)'},
    {title: "Hollywood's Bleeding"},
    {title: 'Future Nostalgia (The Moonlight Edition)'},
    {title: 'x (Wembley Edition)'},
    {title: 'WHEN WE ALL FALL ASLEEP, WHERE DO WE GO?'},
    {title: 'Un Verano Sin Ti'},
    {title: '? (Deluxe)'},
    {title: 'Purpose (Deluxe)'},
    {title: 'Scorpion'},
    {title: 'After Hours (Deluxe)'},
    {title: 'SOUR'},
    {title: 'Starboy'},
    {title: 'Views'},
    {title: 'Stoney (Complete Edition)'},
    {title: 'YHLQMDLG'},
    {title: 'In The Lonely Hour (Drowning Shadows Edition)'},
    {title: 'Beauty Behind The Madness'},
    {title: 'dont smile at me (Expanded Edition'},
    {title: 'Fine Line'},
    {title: 'ASTROWORLD'},
    {title: '17'},
    {title: 'Goodbye and Good Riddance (Anniversary Edition)'}

];

var songs = [
    { title: 'Shape of You'},
    { title: 'Blinding Lights'},
    { title: 'Dance Monkey'},
    { title: 'Rockstar'},
    { title: 'Someone You Loved'},
    { title: 'Sunflower'},
    { title: 'One Dance'},
    { title: 'Closer'},
    { title: 'Believer	'},
    { title: 'Senorita' },
    { title: 'Perfect' },
    { title: 'Stay' },
    { title: 'Bad Guy' },
    { title: "Say You Won't Let Go" },
    { title: 'Thinking Out Loud' },
    { title: 'Heat Waves' },
    { title: 'Lucid Dreams' },
    { title: "Don't Start Now" },
    { title: "God's Plan" },
    { title: 'Starboy' },
    { title: 'Photograph' },
    { title: 'Watermelon Sugar' },
    { title: 'Lovely' },
    { title: 'Bohemian Rhapsody' },
    { title: 'Ghost'}
    // etc
  ];